### PR TITLE
init

### PR DESCRIPTION
**Pull request by mdnika**
some text from `marinadanilov.txt`

### CODE REVIEW

**Review by weizen-w — CHANGES_REQUESTED** [review]
you changed the wrong file, you need to add your txt аfile

**Review by Tanchik88 — APPROVED** [review]
super

**Review by AlexanderNartow — CHANGES_REQUESTED** [review]
error

**Review by sdkinc — APPROVED** [review]

**Review by weizen-w — APPROVED** [review]
ok

**Review by AlexanderNartow — APPROVED** [review]
d

**Pull request merged**
